openapi: 3.0.3
info:
  title: API Version 3 coverage documents API
  version: 3.0.0
  description: "This is the documentation for the public api *(version 3)* of 99minutos. [https://www.99minutos.com/.](https://www.99minutos.com/.EnvironmentAPI)\n\n# First Steps\n\n1.  Create an account in the sandbox website: [https://delivery-git-sandbox-99minutos.vercel.app/](https://delivery-git-sandbox-99minutos.vercel.app/)\n2.  Go to Developers section\n3.  On API Keys V3 section click on `Generar`\n4.  After this the `client_id` and `client_secret` will be displayed\n    \n\nUse the credentials to generate access tokens as shown below in the endpoint `create access token`\n\nFollow the same process in production.\n\n## Environments\n\n| **Environment** | **Website** | **API url** |\n| --- | --- | --- |\n| Sandbox | [https://delivery-git-sandbox-99minutos.vercel.app/](https://delivery-git-sandbox-99minutos.vercel.app/) | [https://sandbox.99minutos.com](https://sandbox.99minutos.com) |\n| Production | [https://envios.99minutos.com/developers](https://envios.99minutos.com/developers) | [https://delivery.99minutos.com](https://delivery.99minutos.com) |\n\n`Each environment has an independent set of credentials`"
servers:
- url: https://delivery.99minutos.com
  description: Produccion
- url: https://sandbox.99minutos.com
  description: Sandbox Environment
tags:
- name: documents
paths:
  /api/v3/documents/guides:
    post:
      operationId: documents_guides_create
      description: 'Return a list of pdf guides for the given identifiers.


        Allowed sizes


        | Value | Description |

        | --- | --- |

        | letter | Document size of 9 x 11 |

        | zebra | Document size of 4 x 6 |

        | small | Document size of 4 x 3 |


        All sizes are inches'
      tags:
      - documents
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GuidesRequest'
            examples:
              ReturnGuidesExample:
                value:
                  guides:
                  - identifier: B345SN3IS2
                    size: zebra
                  - identifier: 648cb66d-2f81-49b9-ab91-eb3937aecc0b
                    size: letter
                summary: Return guides example
                description: Return guides payload
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/GuidesRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/GuidesRequest'
        required: true
      security:
      - AuthJWT: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GuideResponse'
              examples:
                ReturnGuidesResponse:
                  value:
                    traceId: 4dca8e6b-104e-4376-a5ab-ea0690cc0233
                    message: Successful pdf guides.
                    data:
                    - id: B345SN3IS2
                      pdf: JVBERi0xLjQKJZOMi54gUmVwb3J0TGFiIEd
                    - id: 648cb66d-2f81-49b9-ab91-eb3937aecc0b
                      pdf: unknown shipment
                    errors: {}
                  summary: return guides response
                  description: return guides
          description: ''
  /api/v3/documents/zpl:
    post:
      operationId: documents_zpl_create
      description: ZPL returns a list of ZPL based on the received identifiers.
      tags:
      - documents
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ZplRequest'
            examples:
              CreateZplExample:
                value:
                  identifiers:
                  - 648cb66d-2f81-49b9-ab91-eb3937aecc0b
                  - 4fcccf64-82ba-40c0-b6b9-943b7869c2bf
                  - a614197d-c533-4282-91b9-ca9b0d1fcfb8
                summary: Create zpl example
                description: Create zpl payload
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ZplRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ZplRequest'
        required: true
      security:
      - AuthJWT: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ZplResponse'
              examples:
                CreateZplResponse:
                  value:
                    traceId: 061876eb-d0ec-431a-aceb-215ca0039ad0
                    message: Successful ZPL.
                    data:
                    - id: 648cb66d-2f81-49b9-ab91-eb3937aecc0b
                      zpl: "^XA\n                                        ^FO600,20^GB150,120,3^FS\n                                        ^CFA,14\n                                        ^FO610,60^FD Sprint  ^FS\n                                        ^CFA,12\n                                        ^FO610,90^FD Envio de entrega ^FS\n                                        ^FO610,100^FD dia siguiente ^FS\n                                        ^FO 20,20^GFA,1300,1300,13,,:Y018,Y054,Y032,g098,Y080C,X0D003,R018J03I08,T08,N03K03J02002,N0C6O03001,M082CK0880030048,M0EN07K064,L06004L018J014,L08K0108102J019,K01069EK04084J048,L018EL01702001,J03621N0C00124004,J0240CN0880661004,J0819O01I04A008,I01014P01J0C08,L08S0208,I04S018C00E04,J084T02I0C,J024T020098,J09T06101B,00218T02I06,00302T010404,003V0524,008V02,I0CV0C9,0289V061,I04W01,0414V0A1,002J01CK01CJ0208,0028001FFEI01FFEJ028,013I03IF8003IF8I022,011I07IFC00JFCJ02,08J0JFE01JFE00116,026001KF01KF00108,166003FFBFF83FF3FF80108,004003FC07F83FC07F80081,204007F803FC7F803F8008,2J07F001FC7F003FC,3J07F001FC7F001FC,004007F001FC7F001FC00228,104007F001FE7F001FCI03,K07F001FE7F001FE001,K07F001FE7F001FE,K07F803FE7F803FE,K03FC07FE7FC07FE,K03FF1FFE3FF1FFE,1J01KFE3KFE,1J01KFE1KFC,1K0KFC0KFC004,6K07JFC07JFC0021,61J01JFC01JFC0021,2L03E1FC003E3FC002,2N03FCJ03FC002,204L03FCJ03F8J08,204L07F8J07F8,004L07F8J07F8,04M0FFK0FFJ04,2A4I0103FF00103FFJ04,L03IFE003IFEJ05,04J07IFC007IFCJ01,041I0JFC00JFC002,001001JF801JFI0202,001I0IFEI0IFE,0014003FF8I03FF8I01,0408V09,0401V088,0205U01808,0124U0221,01208V01,J08T010A,00C82T0904,00481S018,I082S0246,I0604R0823,I0616Q01002,I08V04,I05404P07064,I02083R088,L038O0317,M04M0183,J01001M06B,K028018L0381,K01R0A,K06K0C0DJ08,K01L02J03,L046N01C,L031N0F,V04,,N07I02038,O0107FE8,Q01,,^FS\n                                        ^CF0,40\n                                        ^FO120,70^FDminutos.com^FS\n                                        ^CFA,18\n                                        ^FO20,150^FD No. De Guia : 939888484  ^FS\n                                        ^FO20,180^FD Fecha de creado : 2021-04-30  ^FS\n                                        ^FO400,130^GB80,80,3^FS\n                                        ^CFA,14\n                                        ^FO380,110^FD Zonificacion ^FS\n                                        ^CFA,13\n                                        ^FO425,170^FD ^FS\n                                        ^CF0,24\n                                        ^FO20,250^FD Origen ^FS\n                                        ^CFA,13\n                                        ^FO20,300^FD Direccion : Viena 4837, Villa Verde, Verde, 80184 Cu - ^FS\n                                        ^CFA,13\n                                        ^FO20,335^FD liacán Rosales, Sin., México,,80184,mex  ^FS\n                                        ^FO20,365^FD   ^FS\n                                        ^CFA,14\n                                        ^FO20,400^FD Remitente : Alfonso  ^FS\n                                        ^CF0,24\n                                        ^FO20,450^FD Destino ^FS\n                                        ^CFA,13\n                                        ^FO20,490^FD Direccion : C.Monte Camerun 145, Lomas de Chapultepe -  ^FS\n                                        ^FO20,520^FD c, Miguel Hidalgo, 11000 Ciudad de Méxic  ^FS\n                                        ^FO20,560^FD éxico,,11000,MEX  ^FS\n                                        ^CFA,14\n                                        ^FO20,590^FD Destinatario :  ^FS\n                                        ^FO20,620^FD  Pedro Salas  ^FS\n                                        ^CF0,24\n                                        ^FO390,250^FD Informacion del pedido ^FS\n                                        ^CFA,18\n                                         ^CI28\n                                        ^FO390,300^FD Tamaño : dia siguiente  ^FS\n                                        ^FO390,340^FD Modalidad : Sprint  ^FS\n                                        ^CF0,24\n                                        ^FO390,450^FD Especificaciones ^FS\n                                        ^CFA,18\n                                        ^FO390,490^FD Cobro : No  ^FS\n                                        ^FO390,520^FD Recolecta : Alfonso  ^FS\n                                        ^FO390,570^FD Notas : #id | Cobro: No |  Recibe: Pedro Salas | Recolecta con: Alfo  ^FS\n                                        ^CFA,13\n                                        ^FO390,600^FD  nso | Orden de prueb  ^FS\n                                        ^FO390,620^FD  acking  ^FS\n                                        ^FO390,640^FD    ^FS\n                                        ^FX\n                                        ^FO50,690^GB700,250,3^FS\n                                        ^FO400,690^GB1,230,3^FS\n                                        ^CF0,40\n                                        ^FO150,750^BQ,2,6^FDLA 939888484 ^FS\n                                        ^CF0,190\n                                        ^FO470,955^FD\n                                        ^BY2,1,150\n                                        ^FO430,720^BC^FD 939888484 ^FS\n                                        ^FS\n                                        ^XZ"
                    - id: 4fcccf64-82ba-40c0-b6b9-943b7869c2bf
                      zpl: "^XA\n                                        ^FO600,20^GB150,120,3^FS\n                                        ^CFA,14\n                                        ^FO610,60^FD Sprint  ^FS\n                                        ^CFA,12\n                                        ^FO610,90^FD Envio de entrega ^FS\n                                        ^FO610,100^FD dia siguiente ^FS\n                                        ^FO 20,20^GFA,1300,1300,13,,:Y018,Y054,Y032,g098,Y080C,X0D003,R018J03I08,T08,N03K03J02002,N0C6O03001,M082CK0880030048,M0EN07K064,L06004L018J014,L08K0108102J019,K01069EK04084J048,L018EL01702001,J03621N0C00124004,J0240CN0880661004,J0819O01I04A008,I01014P01J0C08,L08S0208,I04S018C00E04,J084T02I0C,J024T020098,J09T06101B,00218T02I06,00302T010404,003V0524,008V02,I0CV0C9,0289V061,I04W01,0414V0A1,002J01CK01CJ0208,0028001FFEI01FFEJ028,013I03IF8003IF8I022,011I07IFC00JFCJ02,08J0JFE01JFE00116,026001KF01KF00108,166003FFBFF83FF3FF80108,004003FC07F83FC07F80081,204007F803FC7F803F8008,2J07F001FC7F003FC,3J07F001FC7F001FC,004007F001FC7F001FC00228,104007F001FE7F001FCI03,K07F001FE7F001FE001,K07F001FE7F001FE,K07F803FE7F803FE,K03FC07FE7FC07FE,K03FF1FFE3FF1FFE,1J01KFE3KFE,1J01KFE1KFC,1K0KFC0KFC004,6K07JFC07JFC0021,61J01JFC01JFC0021,2L03E1FC003E3FC002,2N03FCJ03FC002,204L03FCJ03F8J08,204L07F8J07F8,004L07F8J07F8,04M0FFK0FFJ04,2A4I0103FF00103FFJ04,L03IFE003IFEJ05,04J07IFC007IFCJ01,041I0JFC00JFC002,001001JF801JFI0202,001I0IFEI0IFE,0014003FF8I03FF8I01,0408V09,0401V088,0205U01808,0124U0221,01208V01,J08T010A,00C82T0904,00481S018,I082S0246,I0604R0823,I0616Q01002,I08V04,I05404P07064,I02083R088,L038O0317,M04M0183,J01001M06B,K028018L0381,K01R0A,K06K0C0DJ08,K01L02J03,L046N01C,L031N0F,V04,,N07I02038,O0107FE8,Q01,,^FS\n                                        ^CF0,40\n                                        ^FO120,70^FDminutos.com^FS\n                                        ^CFA,18\n                                        ^FO20,150^FD No. De Guia : 939888484  ^FS\n                                        ^FO20,180^FD Fecha de creado : 2021-04-30  ^FS\n                                        ^FO400,130^GB80,80,3^FS\n                                        ^CFA,14\n                                        ^FO380,110^FD Zonificacion ^FS\n                                        ^CFA,13\n                                        ^FO425,170^FD ^FS\n                                        ^CF0,24\n                                        ^FO20,250^FD Origen ^FS\n                                        ^CFA,13\n                                        ^FO20,300^FD Direccion : Viena 4837, Villa Verde, Verde, 80184 Cu - ^FS\n                                        ^CFA,13\n                                        ^FO20,335^FD liacán Rosales, Sin., México,,80184,mex  ^FS\n                                        ^FO20,365^FD   ^FS\n                                        ^CFA,14\n                                        ^FO20,400^FD Remitente : Alfonso  ^FS\n                                        ^CF0,24\n                                        ^FO20,450^FD Destino ^FS\n                                        ^CFA,13\n                                        ^FO20,490^FD Direccion : C.Monte Camerun 145, Lomas de Chapultepe -  ^FS\n                                        ^FO20,520^FD c, Miguel Hidalgo, 11000 Ciudad de Méxic  ^FS\n                                        ^FO20,560^FD éxico,,11000,MEX  ^FS\n                                        ^CFA,14\n                                        ^FO20,590^FD Destinatario :  ^FS\n                                        ^FO20,620^FD  Pedro Salas  ^FS\n                                        ^CF0,24\n                                        ^FO390,250^FD Informacion del pedido ^FS\n                                        ^CFA,18\n                                         ^CI28\n                                        ^FO390,300^FD Tamaño : dia siguiente  ^FS\n                                        ^FO390,340^FD Modalidad : Sprint  ^FS\n                                        ^CF0,24\n                                        ^FO390,450^FD Especificaciones ^FS\n                                        ^CFA,18\n                                        ^FO390,490^FD Cobro : No  ^FS\n                                        ^FO390,520^FD Recolecta : Alfonso  ^FS\n                                        ^FO390,570^FD Notas : #id | Cobro: No |  Recibe: Pedro Salas | Recolecta con: Alfo  ^FS\n                                        ^CFA,13\n                                        ^FO390,600^FD  nso | Orden de prueb  ^FS\n                                        ^FO390,620^FD  acking  ^FS\n                                        ^FO390,640^FD    ^FS\n                                        ^FX\n                                        ^FO50,690^GB700,250,3^FS\n                                        ^FO400,690^GB1,230,3^FS\n                                        ^CF0,40\n                                        ^FO150,750^BQ,2,6^FDLA 939888484 ^FS\n                                        ^CF0,190\n                                        ^FO470,955^FD\n                                        ^BY2,1,150\n                                        ^FO430,720^BC^FD 939888484 ^FS\n                                        ^FS\n                                        ^XZ"
                    errors: {}
                  summary: Create zpl response
                  description: Create zpl response
          description: ''
components:
  schemas:
    Zpl:
      type: object
      properties:
        id:
          type: string
        zpl:
          type: string
      required:
      - id
      - zpl
    GuideSizeEnum:
      enum:
      - letter
      - zebra
      - small
      type: string
    ZplResponse:
      type: object
      properties:
        message:
          type: string
        traceId:
          type: string
          format: uuid
        data:
          type: array
          items:
            $ref: '#/components/schemas/Zpl'
        errors:
          type: object
          additionalProperties: {}
      required:
      - data
      - errors
      - message
      - traceId
    Guide:
      type: object
      properties:
        identifier:
          type: string
          description: The identifier represent a internalKey or trackingId of one shipment.
        size:
          allOf:
          - $ref: '#/components/schemas/GuideSizeEnum'
          description: All sizes are inches<br/>letter -> Document size of 9 x 11<br/>zebra -> Document size of 6 x 8<br/>small -> Document size of 4 x 6<br/>
      required:
      - identifier
      - size
    GuidesRequest:
      type: object
      properties:
        guides:
          type: array
          items:
            $ref: '#/components/schemas/Guide'
      required:
      - guides
    ZplRequest:
      type: object
      properties:
        identifiers:
          type: array
          items:
            type: string
          description: The identifier represent a internalKey or trackingId of one shipment.
      required:
      - identifiers
    GuideResponse:
      type: object
      properties:
        message:
          type: string
        traceId:
          type: string
          format: uuid
        data:
          type: array
          items:
            $ref: '#/components/schemas/GuideList'
      required:
      - data
      - message
      - traceId
    GuideList:
      type: object
      properties:
        id:
          type: string
        pdf:
          type: string
      required:
      - id
      - pdf
  securitySchemes:
    AuthJWT:
      type: http
      scheme: bearer
      bearerFormat: JWT
